name: Canary Monitor

on:
  schedule:
    # Запуск що 2години (на початку кожної години)
   - cron: '05 0,3,6,9,12,15,18,21 * * *'
  workflow_dispatch:
    # Цей блок дозволяє запускати скрипт вручну кнопкою

jobs:
  run-canary:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Kyiv
    steps:
    - name: Отримання коду
      uses: actions/checkout@v3

    - name: Встановлення Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Встановлення бібліотек
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Запуск Canary Скрипта
      env:
        M2M_EMAIL: ${{ secrets.M2M_EMAIL }}
        M2M_PASSWORD: ${{ secrets.M2M_PASSWORD }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_DM_CHAT_ID: ${{ secrets.TELEGRAM_DM_CHAT_ID }}
      run: python canary.py
